# Server
[server]
port = "8081"

# Telegraf
[telegraf]
host = ""

# Rig
[rig]
URL = "https://rig-dev.xplex.online"

# Nginx
[nginx]

  [nginx.sec]
  configBasePath = "/home/xplex/etc/stub"
  pidBasePath = "/home/xplex/etc/pid"
  configStubPath = "assets/nginx.conf"

  [nginx.pri]
  statsURL = ""
  controlURL = ""