# Server
[server]
port = "8086"

# Telegraf
[telegraf]
host = ""

# Rig
[rig]
URL = ""

# Nginx
[nginx]

  [nginx.sec]
  configBasePath = ""
  pidBasePath = ""
  configStubPath = ""

  [nginx.pri]
  statsURL = ""
  controlURL = ""